/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


int main(void)
{
	//Clock Mem Mapping
	//Memory Map + Offset
	uint32_t *ClckCtrlReset=(uint32_t*)0x40023830;
	uint32_t *GpioModeSet=(uint32_t*)0x40020C00;
	uint32_t *GpioPinStatus=(uint32_t*)0x40020C14;


	//Enable clock
	*ClckCtrlReset|=0x0008;
//	*ClckCtrlReset|=0x80;
	//clear the bits for the pin needed(31 and 30)
	*GpioModeSet&=0x3FFFFFFF;
	//Set the 32 and 30 pins to output Mode(01)
	*GpioModeSet|=0x40000000;
	//set pin 15 to high
	 *GpioPinStatus|=0x8000;


	 while(1);





    /* Loop forever */
	//for(;;);
}
